version: '3'

networks:
  mynetwork:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5451:5432"
    volumes:
      - ./src/postgres:/docker-entrypoint-initdb.d

  go-app:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - postgres
    ports:
      - "3333:3333"
