version: '3'

networks:
  mynetwork:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - mynetwork  # Aqui adicionamos a rede

  go-app:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    networks:
      - mynetwork  # Também adicionamos a rede
